export default data = [
    {
        "id": "01523028-7151-4404-9F9B-4B1CE778B58F",
        "element": "TwoColumnRow",
        "text": "Two Column Row",
        "required": false,
        "canHavePageBreakBefore": true,
        "canHaveAlternateForm": true,
        "canHaveDisplayHorizontal": true,
        "canHaveOptionCorrect": true,
        "canHaveOptionValue": true,
        "canPopulateFromApi": true,
        "field_name": "two_col_row_DE114F5A-4B27-4F99-9497-E71D3EE17FF4",
        "childItems": [
            "3EBC93AE-5552-4796-B699-D806D0374309",
            "8A6C0F28-863A-4B59-9419-F128A1F22B58"
        ],
        "isContainer": true
    },
    {
        "id": "1B07FFF6-6437-4425-83F2-9938BC0609EC",
        "element": "ThreeColumnRow",
        "text": "Three Column Row",
        "required": false,
        "canHavePageBreakBefore": true,
        "canHaveAlternateForm": true,
        "canHaveDisplayHorizontal": true,
        "canHaveOptionCorrect": true,
        "canHaveOptionValue": true,
        "canPopulateFromApi": true,
        "field_name": "three_col_row_23390413-C9FF-4E06-AB9D-CADEE616D764",
        "childItems": [
            "AD6F82E4-807E-45BA-A852-3470DCB162BF",
            "204BA3FD-B9A9-4A78-8155-B7ECBE580A68",
            "B88CE87B-B45C-47CF-8013-63054F47355E"
        ],
        "isContainer": true
    },
    {
        "id": "B68B2922-F5AD-4695-9A01-1B410650776D",
        "element": "TwoColumnRow",
        "text": "Two Column Row",
        "required": false,
        "canHavePageBreakBefore": true,
        "canHaveAlternateForm": true,
        "canHaveDisplayHorizontal": true,
        "canHaveOptionCorrect": true,
        "canHaveOptionValue": true,
        "canPopulateFromApi": true,
        "field_name": "two_col_row_4E64350F-E137-49B9-B76A-29CD3EC8B089",
        "childItems": [
            "E3362B38-FF33-4F7B-A33D-B904A05F4FE3",
            "854017F9-4E0F-4EB0-B038-212240B06F76"
        ],
        "isContainer": true
    },
    {
        "id": "04DF4682-C6AA-4FFC-A7EF-B52CF186BCA5",
        "element": "TwoColumnRow",
        "text": "Two Column Row",
        "required": false,
        "canHavePageBreakBefore": true,
        "canHaveAlternateForm": true,
        "canHaveDisplayHorizontal": true,
        "canHaveOptionCorrect": true,
        "canHaveOptionValue": true,
        "canPopulateFromApi": true,
        "field_name": "two_col_row_6E97EE73-32A4-4C86-A597-661A71A6A6E5",
        "childItems": [
            "6D69C7B8-C896-4CE7-8CDA-A04963EC3C24",
            "09C53AF5-3854-42A0-8870-390BE3BE901E"
        ],
        "isContainer": true
    },
    {
        "id": "3EBC93AE-5552-4796-B699-D806D0374309",
        "element": "TextInput",
        "text": "Text Input",
        "required": true,
        "canHaveAnswer": true,
        "canHavePageBreakBefore": true,
        "canHaveAlternateForm": true,
        "canHaveDisplayHorizontal": true,
        "canHaveOptionCorrect": true,
        "canHaveOptionValue": true,
        "canPopulateFromApi": true,
        "field_name": "first",
        "label": "First name ",
        "col": 0,
        "parentId": "01523028-7151-4404-9F9B-4B1CE778B58F",
        "parentIndex": 0,
        "dirty": false
    },
    {
        "id": "8A6C0F28-863A-4B59-9419-F128A1F22B58",
        "element": "TextInput",
        "text": "Text Input",
        "required": true,
        "canHaveAnswer": true,
        "canHavePageBreakBefore": true,
        "canHaveAlternateForm": true,
        "canHaveDisplayHorizontal": true,
        "canHaveOptionCorrect": true,
        "canHaveOptionValue": true,
        "canPopulateFromApi": true,
        "field_name": "last",
        "label": "Last name ",
        "col": 1,
        "parentId": "01523028-7151-4404-9F9B-4B1CE778B58F",
        "parentIndex": 0,
        "dirty": false
    },
    {
        "id": "AD6F82E4-807E-45BA-A852-3470DCB162BF",
        "element": "TextInput",
        "text": "Text Input",
        "required": true,
        "canHaveAnswer": true,
        "canHavePageBreakBefore": true,
        "canHaveAlternateForm": true,
        "canHaveDisplayHorizontal": true,
        "canHaveOptionCorrect": true,
        "canHaveOptionValue": true,
        "canPopulateFromApi": true,
        "field_name": "mrn",
        "label": "MRN ",
        "col": 0,
        "parentId": "1B07FFF6-6437-4425-83F2-9938BC0609EC",
        "parentIndex": 1,
        "dirty": false
    },
    {
        "id": "204BA3FD-B9A9-4A78-8155-B7ECBE580A68",
        "element": "DatePicker",
        "text": "Date",
        "required": true,
        "readOnly": false,
        "defaultToday": false,
        "canHavePageBreakBefore": true,
        "canHaveAlternateForm": true,
        "canHaveDisplayHorizontal": true,
        "canHaveOptionCorrect": true,
        "canHaveOptionValue": true,
        "canPopulateFromApi": true,
        "dateFormat": "MM/dd/yyyy",
        "timeFormat": "hh:mm aa",
        "showTimeSelect": false,
        "showTimeSelectOnly": false,
        "field_name": "birth_date",
        "label": "Birth Date ",
        "col": 1,
        "parentId": "1B07FFF6-6437-4425-83F2-9938BC0609EC",
        "parentIndex": 1,
        "dirty": false
    },
    {
        "id": "B88CE87B-B45C-47CF-8013-63054F47355E",
        "element": "Dropdown",
        "text": "Dropdown",
        "required": false,
        "canHaveAnswer": true,
        "canHavePageBreakBefore": true,
        "canHaveAlternateForm": true,
        "canHaveDisplayHorizontal": true,
        "canHaveOptionCorrect": true,
        "canHaveOptionValue": true,
        "canPopulateFromApi": true,
        "field_name": "sex",
        "label": "Gender",
        "options": [
            {
                "value": "select",
                "text": "Select",
                "key": "dropdown_option_7C65AB3D-7CED-4DA0-8802-F679304BC74E"
            },
            {
                "value": "F",
                "text": "Female",
                "key": "35EEAA3F-210E-42B7-AE5B-628D1BF24A0A"
            },
            {
                "value": "M",
                "text": "Male",
                "key": "dropdown_option_F739A279-3CE6-42AD-9CB8-A75E20F588F9"
            },
            {
                "value": "O",
                "text": "Other",
                "key": "dropdown_option_68A0ACF7-EE5E-441F-A313-3C1342D8C87E"
            }
        ],
        "col": 2,
        "parentId": "1B07FFF6-6437-4425-83F2-9938BC0609EC",
        "parentIndex": 1,
        "dirty": false
    },
    {
        "id": "E3362B38-FF33-4F7B-A33D-B904A05F4FE3",
        "element": "TextInput",
        "text": "Text Input",
        "required": false,
        "canHaveAnswer": true,
        "canHavePageBreakBefore": true,
        "canHaveAlternateForm": true,
        "canHaveDisplayHorizontal": true,
        "canHaveOptionCorrect": true,
        "canHaveOptionValue": true,
        "canPopulateFromApi": true,
        "field_name": "email",
        "label": "Email",
        "col": 0,
        "parentId": "B68B2922-F5AD-4695-9A01-1B410650776D",
        "parentIndex": 2,
        "dirty": false
    },
    {
        "id": "854017F9-4E0F-4EB0-B038-212240B06F76",
        "element": "TextInput",
        "text": "Text Input",
        "required": false,
        "canHaveAnswer": true,
        "canHavePageBreakBefore": true,
        "canHaveAlternateForm": true,
        "canHaveDisplayHorizontal": true,
        "canHaveOptionCorrect": true,
        "canHaveOptionValue": true,
        "canPopulateFromApi": true,
        "field_name": "alt_email",
        "label": "Alternative Email",
        "col": 1,
        "parentId": "B68B2922-F5AD-4695-9A01-1B410650776D",
        "parentIndex": 2,
        "dirty": false
    },
    {
        "id": "6D69C7B8-C896-4CE7-8CDA-A04963EC3C24",
        "element": "TextInput",
        "text": "Text Input",
        "required": false,
        "canHaveAnswer": true,
        "canHavePageBreakBefore": true,
        "canHaveAlternateForm": true,
        "canHaveDisplayHorizontal": true,
        "canHaveOptionCorrect": true,
        "canHaveOptionValue": true,
        "canPopulateFromApi": true,
        "field_name": "mobile_phone",
        "label": "Mobile Phone",
        "col": 0,
        "parentId": "04DF4682-C6AA-4FFC-A7EF-B52CF186BCA5",
        "parentIndex": 3,
        "dirty": false
    },
    {
        "id": "09C53AF5-3854-42A0-8870-390BE3BE901E",
        "element": "TextInput",
        "text": "Text Input",
        "required": false,
        "canHaveAnswer": true,
        "canHavePageBreakBefore": true,
        "canHaveAlternateForm": true,
        "canHaveDisplayHorizontal": true,
        "canHaveOptionCorrect": true,
        "canHaveOptionValue": true,
        "canPopulateFromApi": true,
        "field_name": "alt_phone",
        "label": "Alternative phone ",
        "col": 1,
        "parentId": "04DF4682-C6AA-4FFC-A7EF-B52CF186BCA5",
        "parentIndex": 3,
        "dirty": false
    }
]
